{% set version = "1.4.0" %}

package:
  name: pvxs
  version: "{{ version }}"

source:
  url: https://github.com/epics-base/pvxs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 10d11809ad1e9049d0b85260b1e417570f07c2d468494064dcf0abeac090ed16
  patches:
    - 0001-Add-environment-variable-for-softIocPVX.dbd.patch
    - 0002-Workaround-cfg-include-bug.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('pvxs', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}  # [linux]
    - {{ compiler('cxx') }}
    - make
    - perl
    - m2-patch  # [win]
  host:
    - epics-base
    - libevent

test:
  commands:
    - pvxcall -V
    - pvxget -V
    - pvxinfo -V
    - pvxlist -V
    - pvxmonitor -V
    - pvxmshim -V
    - pvxput -V
    - pvxvct -V
    - softIocPVX -V
  files:
    - lib/libpvxs.so  # [linux]
    - lib/libpvxsIoc.so  # [linux]
    - lib/libpvxs.dylib  # [osx]
    - lib/libpvxsIoc.dylib  # [osx]
    # Windows DLLs go into bin/
    - bin/pvxs.dll  # [win]
    - bin/pvxsIoc.dll  # [win]
    - lib/pvxs.lib  # [win]
    - lib/pvxsIoc.lib  # [win]
    # EPICS base DLLs
    - bin/Com.dll  # [win]
    - bin/dbCore.dll  # [win]
    - bin/dbRecStd.dll  # [win]
    - include/pvxs/version.h

about:
  home: https://github.com/epics-base/pvxs/
  license: BSD-4-Clause-UC
  license_family: BSD
  license_file: LICENSE
  summary: Library and a set of CLI utilities acting as PVAccess protocol client and/or server
  doc_url: https://epics-base.github.io/pvxs/

extra:
  recipe-maintainers:
    - anderslindho
    - lucmaga
    - aharrisson
    - simon-ess
