schema_version: 1

context:
  version: "1.4.1"

recipe:
  name: pvxs-split
  version: ${{ version }}

source:
  url: https://github.com/epics-base/pvxs/archive/refs/tags/${{ version }}.tar.gz
  sha256: 96a41cf88ea7e4f608840c713edfc9ed9a70b5e9d0ff0813647ed518b227af10
  patches:
    - 0001-Add-environment-variable-for-softIocPVX.dbd.patch
    - 0002-Workaround-cfg-include-bug.patch

build:
  number: 2

outputs:
  - package:
      name: pvxs
      version: ${{ version }}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - make
        - perl
        - if: win
          then: m2-patch
      host:
        - epics-base
        - libevent
      run_exports:
        - ${{ pin_subpackage('pvxs', upper_bound='x.x.x') }}
    tests:
      - files:
          recipe:
            - if: linux
              then:
                - lib/libpvxs.so
                - lib/libpvxsIoc.so
            - if: osx
              then:
                - lib/libpvxs.dylib
                - lib/libpvxsIoc.dylib
            - if: win
              then:
                - Library/bin/pvxs.dll
                - Library/bin/pvxsIoc.dll
                - Library/lib/pvxs.lib
                - Library/lib/pvxsIoc.lib
            - include/pvxs/version.h
        script:
          - pvxcall -V
          - pvxget -V
          - pvxinfo -V
          - pvxlist -V
          - pvxmonitor -V
          - pvxmshim -V
          - pvxput -V
          - pvxvct -V
          - softIocPVX -V
    build:
      script:
        - if: unix
          then: build-pvxs.sh
        - if: win
          then: build-pvxs.bat

  - package:
      name: pvxslibs
      version: ${{ version }}
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - python
        - pip
        - setuptools_dso
      host:
        - python
        - pip
        - setuptools
        - setuptools_dso
        - epicscorelibs
        - ${{ pin_subpackage('pvxs', exact=True) }}
      run:
        - python
        - ${{ pin_subpackage('pvxs', exact=True) }}
        - epicscorelibs
    tests:
      - python:
          imports:
            - pvxslibs
    build:
      script:
        - pip install . --no-deps --no-build-isolation -vv

about:
  license: BSD-4-Clause-UC
  license_file: LICENSE
  summary: Python bindings for PVXS library
  homepage: https://github.com/epics-base/pvxs/
  documentation: https://epics-base.github.io/pvxs/

extra:
  recipe-maintainers:
    - anderslindho
    - lucmaga
    - aharrisson
    - simon-ess
