schema_version: 1

context:
  version: 1.4.0

package:
  name: pvxs
  version: ${{ version }}

source:
  url: https://github.com/epics-base/pvxs/archive/refs/tags/${{ version }}.tar.gz
  sha256: 10d11809ad1e9049d0b85260b1e417570f07c2d468494064dcf0abeac090ed16
  patches:
    - 0001-Add-environment-variable-for-softIocPVX.dbd.patch
    - 0002-Workaround-cfg-include-bug.patch

build:
  number: 5

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - make
    - perl
    - if: win
      then: m2-patch
  host:
    - epics-base
    - libevent
  run_exports:
    - ${{ pin_subpackage('pvxs', upper_bound='x.x.x') }}

tests:
  - files:
      recipe:
        - if: linux
          then: lib/libpvxs.so
        - if: linux
          then: lib/libpvxsIoc.so
        - if: osx
          then: lib/libpvxs.dylib
        - if: osx
          then: lib/libpvxsIoc.dylib
        - if: win
          then: Library/bin/pvxs.dll
        - if: win
          then: Library/bin/pvxsIoc.dll
        - if: win
          then: Library/lib/pvxs.lib
        - if: win
          then: Library/lib/pvxsIoc.lib
        - include/pvxs/version.h
    script:
      - pvxcall -V
      - pvxget -V
      - pvxinfo -V
      - pvxlist -V
      - pvxmonitor -V
      - pvxmshim -V
      - pvxput -V
      - pvxvct -V
      - softIocPVX -V

about:
  license: BSD-4-Clause-UC
  license_file: LICENSE
  summary: Library and a set of CLI utilities acting as PVAccess protocol client and/or server
  homepage: https://github.com/epics-base/pvxs/
  documentation: https://epics-base.github.io/pvxs/

extra:
  recipe-maintainers:
    - anderslindho
    - lucmaga
    - aharrisson
    - simon-ess
